
env:
   global:
     - CONAN_REFERENCE: "ogre3d/1.12.5"
     - CONAN_USERNAME: "utopia"
     - CONAN_LOGIN_USERNAME: "konradnotantoo"
     - CONAN_STABLE_BRANCH_PATTERN: "release/*"
     - CONAN_CHANNEL: "testing"
     - CONAN_UPLOAD: "https://api.bintray.com/conan/konradnotantoo/utopia"
     - CONAN_REMOTES: "https://api.bintray.com/conan/bincrafters/public-conan"
     - CONAN_BUILD_POLICY: "missing"

linux: &linux
   os: linux
   dist: xenial
   language: python
   python: "3.7"
   services:
     - docker
osx: &osx
   os: osx
   language: generic
matrix:
   include:

      - <<: *linux
        env: CONAN_GCC_VERSIONS=6 CONAN_DOCKER_IMAGE=conanio/gcc6 CONAN_ARCHS=x86 CONAN_OPTIONS=ogre3d:with_cg=False
      - <<: *linux
        env: CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=conanio/gcc7 CONAN_ARCHS=x86 CONAN_OPTIONS=ogre3d:with_cg=False
      - <<: *linux
        env: CONAN_GCC_VERSIONS=8 CONAN_DOCKER_IMAGE=conanio/gcc8 CONAN_ARCHS=x86 CONAN_OPTIONS=ogre3d:with_cg=False
      # Following build fails because build time > 50min, mostly because pre-built conan deps aren't available
      # - <<: *linux
      #   env: CONAN_GCC_VERSIONS=9 CONAN_DOCKER_IMAGE=conanio/gcc9 CONAN_ARCHS=x86 CONAN_OPTIONS=ogre3d:with_cg=False

      - <<: *linux
        env: CONAN_GCC_VERSIONS=6 CONAN_DOCKER_IMAGE=conanio/gcc6 CONAN_ARCHS=x86_64 CONAN_OPTIONS=ogre3d:with_cg=False
      - <<: *linux
        env: CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=conanio/gcc7 CONAN_ARCHS=x86_64 CONAN_OPTIONS=ogre3d:with_cg=False
      - <<: *linux
        env: CONAN_GCC_VERSIONS=8 CONAN_DOCKER_IMAGE=conanio/gcc8 CONAN_ARCHS=x86_64 CONAN_OPTIONS=ogre3d:with_cg=False
      - <<: *linux
        env: CONAN_GCC_VERSIONS=9 CONAN_DOCKER_IMAGE=conanio/gcc9 CONAN_ARCHS=x86_64 CONAN_OPTIONS=ogre3d:with_cg=False

      - <<: *linux
        env: CONAN_GCC_VERSIONS=6 CONAN_DOCKER_IMAGE=conanio/gcc6 CONAN_ARCHS=x86 CONAN_OPTIONS=ogre3d:with_cg=True
      - <<: *linux
        env: CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=conanio/gcc7 CONAN_ARCHS=x86 CONAN_OPTIONS=ogre3d:with_cg=True
      - <<: *linux
        env: CONAN_GCC_VERSIONS=8 CONAN_DOCKER_IMAGE=conanio/gcc8 CONAN_ARCHS=x86 CONAN_OPTIONS=ogre3d:with_cg=True
      # Following build fails because build time > 50min, mostly because pre-built conan deps aren't available
      # - <<: *linux
      #   env: CONAN_GCC_VERSIONS=9 CONAN_DOCKER_IMAGE=conanio/gcc9 CONAN_ARCHS=x86 CONAN_OPTIONS=ogre3d:with_cg=True

      - <<: *linux
        env: CONAN_GCC_VERSIONS=6 CONAN_DOCKER_IMAGE=conanio/gcc6 CONAN_ARCHS=x86_64 CONAN_OPTIONS=ogre3d:with_cg=True
      - <<: *linux
        env: CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=conanio/gcc7 CONAN_ARCHS=x86_64 CONAN_OPTIONS=ogre3d:with_cg=True
      - <<: *linux
        env: CONAN_GCC_VERSIONS=8 CONAN_DOCKER_IMAGE=conanio/gcc8 CONAN_ARCHS=x86_64 CONAN_OPTIONS=ogre3d:with_cg=True
      - <<: *linux
        env: CONAN_GCC_VERSIONS=9 CONAN_DOCKER_IMAGE=conanio/gcc9 CONAN_ARCHS=x86_64 CONAN_OPTIONS=ogre3d:with_cg=True

      # - <<: *linux
      #   env: CONAN_CLANG_VERSIONS=3.9 CONAN_DOCKER_IMAGE=conanio/clang39
      # - <<: *linux
      #   env: CONAN_CLANG_VERSIONS=4.0 CONAN_DOCKER_IMAGE=conanio/clang40
      # - <<: *linux
      #   env: CONAN_CLANG_VERSIONS=5.0 CONAN_DOCKER_IMAGE=conanio/clang50
      # - <<: *linux
      #   env: CONAN_CLANG_VERSIONS=6.0 CONAN_DOCKER_IMAGE=conanio/clang60
      # - <<: *linux
      #   env: CONAN_CLANG_VERSIONS=7.0 CONAN_DOCKER_IMAGE=conanio/clang7
      # - <<: *linux
      #   env: CONAN_CLANG_VERSIONS=8 CONAN_DOCKER_IMAGE=conanio/clang8

install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh

script:
  - chmod +x .travis/run.sh
  - ./.travis/run.sh
