build: false

environment:
    PYTHON: "C:\\Python37"

    CONAN_REFERENCE: "ogre3d/1.12.5"
    CONAN_USERNAME: "utopia"
    CONAN_LOGIN_USERNAME: "konradnotantoo"
    CONAN_STABLE_BRANCH_PATTERN: "release/*"
    CONAN_CHANNEL: "testing"
    CONAN_UPLOAD: "https://api.bintray.com/conan/konradnotantoo/utopia"
    CONAN_REMOTES: "https://api.bintray.com/conan/bincrafters/public-conan"
    CONAN_BUILD_POLICY: "missing"

    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 14
          CI_OGRE_ARCHITECTURE: "x86"
          CI_OGRE_WITH_CG: "OFF"
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          CI_OGRE_ARCHITECTURE: "x86"
          CI_OGRE_WITH_CG: "OFF"
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
          CONAN_VISUAL_VERSIONS: 16
          CI_OGRE_ARCHITECTURE: "x86"
          CI_OGRE_WITH_CG: "OFF"

        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 14
          CI_OGRE_ARCHITECTURE: "x86_64"
          CI_OGRE_WITH_CG: "OFF"
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          CI_OGRE_ARCHITECTURE: "x86_64"
          CI_OGRE_WITH_CG: "OFF"
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
          CONAN_VISUAL_VERSIONS: 16
          CI_OGRE_ARCHITECTURE: "x86_64"
          CI_OGRE_WITH_CG: "OFF"

        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 14
          CI_OGRE_ARCHITECTURE: "x86"
          CI_OGRE_WITH_CG: "ON"
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          CI_OGRE_ARCHITECTURE: "x86"
          CI_OGRE_WITH_CG: "ON"
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
          CONAN_VISUAL_VERSIONS: 16
          CI_OGRE_ARCHITECTURE: "x86"
          CI_OGRE_WITH_CG: "ON"

        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 14
          CI_OGRE_ARCHITECTURE: "x86_64"
          CI_OGRE_WITH_CG: "ON"
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          CI_OGRE_ARCHITECTURE: "x86_64"
          CI_OGRE_WITH_CG: "ON"
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
          CONAN_VISUAL_VERSIONS: 16
          CI_OGRE_ARCHITECTURE: "x86_64"
          CI_OGRE_WITH_CG: "ON"


install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan --upgrade
  - pip.exe install conan_package_tools
  - conan user # It creates the conan data directory

test_script:
  - python build.py
